global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'comic-api-oop'
    static_configs:
      - targets: ['comic-api-dod:8080']
    metrics_path: '/metrics'

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'comic-api-oop-local'
    static_configs:
      - targets: [ 'host.docker.internal:5000' ]  # For Windows/Mac
      # - targets: ['172.17.0.1:5000']  # For Linux, use host IP
    metrics_path: '/metrics'